select DISTINCT EMPLOYEE.Fname,EMPLOYEE.Lname,EMPLOYEE.Minit,EMPLOYEE.Super_ssn,EMPLOYEE.Dno,DEPARTMENT.Dname from DEPARTMENT INNER JOIN EMPLOYEE on EMPLOYEE.Super_ssn = DEPARTMENT.Mgr_ssn AND EMPLOYEE.Dno=DEPARTMENT.Dnumber INNER JOIN WORKS_ON on EMPLOYEE.Ssn = WORKS_ON.Essn where (select COUNT(Essn) from WORKS_ON where Hours<40)>=1;

